(() => {
  const root = document.getElementById('app');
  if (!root) return;
  const pageType=()=>{const t=(root.innerText||'').toLowerCase();if(t.includes('control tower'))return'admin';if(t.includes('matched manufacturing jobs'))return'supplier';if(t.includes('source smarter'))return'buyer';return'home'};
  const media={home:'https://images.pexels.com/photos/3822843/pexels-photo-3822843.jpeg?auto=compress&cs=tinysrgb&w=1800',buyer:'https://images.pexels.com/photos/386236/pexels-photo-386236.jpeg?auto=compress&cs=tinysrgb&w=1800',supplier:'https://images.pexels.com/photos/2760243/pexels-photo-2760243.jpeg?auto=compress&cs=tinysrgb&w=1800',admin:'https://images.pexels.com/photos/8985502/pexels-photo-8985502.jpeg?auto=compress&cs=tinysrgb&w=1800'};
  const copy={
    home:{kicker:'TRUST, BUILT INTO THE JOB',title:'See the people, price and progress behind every order.',sub:'IndustrialConnect connects company evidence, supplier matching, quotations, production and delivery into one visible transaction.',cards:[['01','Verify','Company and capability evidence is shown before a supplier is presented as verified.'],['02','Compare','Structured quotes make price, lead time and commercial terms easier to review.'],['03','Track','Production, quality and dispatch milestones stay attached to the same order.']]},
    buyer:{kicker:'BUYER CONTROL',title:'Buy with visibility, not guesswork.',sub:'See who you are dealing with, what the quote includes and what is happening after the PO.',cards:[['01','Know the supplier','Verification status and capability information appear with the quotation.'],['02','See the full quote','Cost components, GST, lead time and validity are organized in one view.'],['03','Track the order','Production, QC and dispatch evidence stay inside the Order Room.']]},
    supplier:{kicker:'MANUFACTURER CONTROL',title:'Win relevant work with a clear transaction trail.',sub:'Receive structured requirements, submit clear commercial terms and follow the order through production and payout.',cards:[['01','Matched work','RFQs are organized around process, material, quantity and delivery requirements.'],['02','Clear terms','Your quotation and accepted commercial terms remain attached to the order.'],['03','Visible payout','Platform fee and supplier payout status are part of the transaction record.']]},
    admin:{kicker:'OPERATIONS CONTROL',title:'Make exceptions visible before they become expensive.',sub:'Verification gaps, missing QC, delivery issues, disputes and payout exceptions are surfaced in one control layer.',cards:[['01','Verify','Review supplier and company evidence before granting verification.'],['02','Control','Monitor order states, missing documents and operational exceptions.'],['03','Audit','Keep important transaction actions traceable for internal review.']]}
  };
  const steps=[['01','VERIFY','Company + capability'],['02','MATCH','Buyer ↔ manufacturer'],['03','COMPARE','Structured quotations'],['04','EXECUTE','PO + payment + production'],['05','PROVE','QC + dispatch + delivery']];
  function openTrustCenter(){if(document.querySelector('.trust-modal'))return;const modal=document.createElement('div');modal.className='trust-modal';modal.innerHTML=`<div class="trust-modal-box" role="dialog" aria-modal="true"><button class="trust-close" aria-label="Close">×</button><span class="trust-kicker">IndustrialConnect Trust Center</span><h2>Trust is a workflow, not a badge.</h2><p>Verification labels should only be used when the corresponding checks have actually been completed. The platform is designed to keep important commercial and production evidence connected to the transaction.</p>${[['01','Company verification','Business identity and submitted company evidence can be reviewed before verification.'],['02','Capability verification','Machines, processes, materials, tolerances and certifications can be recorded against supplier capabilities.'],['03','Commercial transparency','Quotes use structured cost components and server-side order calculations.'],['04','Transaction record','Accepted quote, PO, payment status, production, quality, shipment and acceptance stay connected.'],['05','Exception handling','Disputes, missing documents, late milestones and payout failures can be routed to operations.'],['06','Access control','Users should only see RFQs, orders, files and messages they are authorized to access.']].map(x=>`<div class="trust-detail"><div class="n">${x[0]}</div><div><b>${x[1]}</b><span>${x[2]}</span></div></div>`).join('')}</div>`;document.body.appendChild(modal);modal.querySelector('.trust-close').onclick=()=>modal.remove();modal.addEventListener('click',e=>{if(e.target===modal)modal.remove()})}
  function renderTrust(){if(!root.querySelector('main')||root.querySelector('.trust-system'))return;const type=pageType(),c=copy[type],host=document.createElement('div');host.className=`trust-system trust-${type}`;host.innerHTML=`<section class="trust-panel" style="--trust-photo:url('${media[type]}')"><div class="trust-photo" aria-hidden="true"></div><div class="trust-noise" aria-hidden="true"></div><div class="trust-scan" aria-hidden="true"></div><div class="trust-content"><div class="trust-top"><div class="trust-copy"><span class="trust-kicker">${c.kicker}</span><h3>${c.title}</h3><p>${c.sub}</p><div class="trust-inline"><span>Company evidence</span><span>Structured quotes</span><span>Order traceability</span></div></div><div class="trust-live"><span class="trust-live-dot"></span><b>TRANSACTION VISIBILITY</b><small>Evidence moves with the order.</small></div></div><div class="trust-steps">${steps.map((s,i)=>`<button class="trust-step trust-reveal ${i===0?'is-live':''}" data-step="${i}"><span class="trust-num">${s[0]}</span><strong>${s[1]}</strong><em>${s[2]}</em><i></i></button>`).join('')}</div><div class="trust-cards">${c.cards.map(x=>`<article class="trust-card trust-reveal"><span class="trust-card-no">${x[0]}</span><div><b>${x[1]}</b><p>${x[2]}</p></div><span class="trust-arrow">↗</span></article>`).join('')}</div><div class="trust-footer"><span>Trust is earned through completed checks and transaction evidence.</span><button class="trust-link" type="button">Open Trust Center ↗</button></div></div></section>`;const main=root.querySelector('main');if(main){const hero=main.querySelector('.hero');if(type==='home'&&hero)hero.insertAdjacentElement('afterend',host);else main.prepend(host)}host.querySelector('.trust-link').onclick=openTrustCenter;const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});host.querySelectorAll('.trust-reveal').forEach(el=>observer.observe(el));const rows=[...host.querySelectorAll('.trust-step')];let current=0,timer;const activate=n=>{rows.forEach((x,i)=>x.classList.toggle('is-live',i===n));current=n};const play=()=>{clearInterval(timer);timer=setInterval(()=>activate((current+1)%rows.length),2600)};rows.forEach((x,i)=>x.onclick=()=>{activate(i);play()});play()}
  const mo=new MutationObserver(()=>requestAnimationFrame(renderTrust));mo.observe(root,{childList:true,subtree:true});requestAnimationFrame(renderTrust);
})();
