(() => {
  const cfg = window.INDUSTRIALCONNECT_SUPABASE || {};
  if (!window.supabase || !cfg.url || !cfg.anonKey) return;
  const db = window.supabase.createClient(cfg.url, cfg.anonKey);
  const root = document.getElementById('app');
  const esc = v => String(v ?? '').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const money = v => '₹' + Number(v || 0).toLocaleString('en-IN',{maximumFractionDigits:2});
  const status = v => String(v||'').replaceAll('_',' ');
  const shell = (role,title,sub,body) => `<nav class="nav"><div class="container navin"><button class="brand" onclick="go('home')"><span class="mark">IC</span>IndustrialConnect</button><div class="actions"><span class="badge">LIVE</span><button class="btn" onclick="go('dashboard')">Workspace</button><button class="btn" onclick="logout()">Sign out</button></div></div></nav><main class="dash"><div class="container"><div class="dashTop"><div><span class="eyebrow">${esc(role)} workspace · live</span><h1>${esc(title)}</h1><p>${esc(sub)}</p></div>${role==='buyer'?'<button class="btn primary" onclick="openRFQ()">Post requirement</button>':''}</div>${body}</div></main>`;
  async function profile(){const {data:{session}}=await db.auth.getSession();if(!session)return null;const {data}=await db.from('profiles').select('id,full_name,role,company_id,companies(name)').eq('id',session.user.id).single();return data;}
  async function buyer(){const p=await profile();if(!p)return;const [{data:rfqs},{data:orders}]=await Promise.all([db.from('rfqs').select('id,rfq_number,title,quantity,unit,material,status,created_at,categories(name)').eq('buyer_company_id',p.company_id).order('created_at',{ascending:false}),db.from('orders').select('id,order_number,total_amount,status,platform_fee,supplier_payout_amount,commission_percent,created_at').eq('buyer_company_id',p.company_id).order('created_at',{ascending:false})]);root.innerHTML=shell('buyer','Source smarter. Track every order.','Live requirements, quotes and production status.',`<div class="stats"><div class="stat"><small>Active RFQs</small><strong>${rfqs?.length||0}</strong></div><div class="stat"><small>Active orders</small><strong>${(orders||[]).filter(o=>!['completed','cancelled'].includes(o.status)).length}</strong></div><div class="stat"><small>Completed</small><strong>${(orders||[]).filter(o=>o.status==='completed').length}</strong></div><div class="stat"><small>Company</small><strong style="font-size:16px">${esc(p.companies?.name||'Complete profile')}</strong></div></div><div class="panelGrid"><div class="panel"><div class="panelTitle"><h3>Requirements</h3><button class="textBtn" onclick="openRFQ()">+ New RFQ</button></div>${(rfqs||[]).map(r=>`<div class="job"><div><b>${esc(r.title)}</b><span>${esc(r.categories?.name||'')} · ${esc(r.quantity)} ${esc(r.unit)} · ${esc(r.material)}</span><small>${status(r.status)}</small></div><button class="btn" onclick="openRFQDetail('${r.id}')">View →</button></div>`).join('')||'<div class="empty compact">No requirements yet.</div>'}</div><div class="panel"><div class="panelTitle"><h3>Orders</h3></div>${(orders||[]).map(o=>`<div class="orderMini"><div class="row"><b>${esc(o.order_number)}</b><span class="badge">${status(o.status)}</span></div><p>${money(o.total_amount)} · Platform fee ${money(o.platform_fee)}</p><button class="btn" onclick="openLiveOrder('${o.id}')">Open Order Room →</button></div>`).join('')||'<div class="empty compact">Orders appear after a quote is accepted.</div>'}</div></div>`);}
  async function supplier(){const p=await profile();if(!p)return;const {data:sp}=await db.from('supplier_profiles').select('id,verification_status,on_time_rate,quality_rate,companies(name)').eq('user_id',p.id).single();if(!sp){root.innerHTML=shell('supplier','Complete your manufacturer profile.','A supplier profile is required before you can quote matched jobs.',`<div class="panel"><h3>Manufacturer onboarding</h3><p class="muted">Ask an admin to create/verify your supplier profile, or use the onboarding SQL helper from the V2 setup.</p><button class="btn" onclick="go('home')">Back to home</button></div>`);return;}const {data:matches}=await db.from('supplier_matches').select('id,match_score,rfq_id,rfqs(id,title,quantity,unit,material,status,categories(name))').eq('supplier_id',sp.id).order('match_score',{ascending:false});const {data:quotes}=await db.from('quotes').select('id,rfq_id,status,unit_price,quantity').eq('supplier_id',sp.id);root.innerHTML=shell('supplier','Matched manufacturing jobs.','Live RFQs matched to your verified capabilities.',`<div class="stats"><div class="stat"><small>Verification</small><strong style="font-size:16px">${esc(sp.verification_status)}</strong></div><div class="stat"><small>Matched RFQs</small><strong>${matches?.length||0}</strong></div><div class="stat"><small>Quotes</small><strong>${quotes?.length||0}</strong></div><div class="stat"><small>On-time</small><strong>${Number(sp.on_time_rate||0)}%</strong></div></div><div class="panel"><div class="panelTitle"><h3>Matched jobs</h3><span class="badge">Capability based</span></div>${(matches||[]).map(m=>{const q=(quotes||[]).find(x=>x.rfq_id===m.rfq_id);return `<div class="job"><div><b>${esc(m.rfqs?.title||'RFQ')}</b><span>${esc(m.rfqs?.categories?.name||'')} · ${esc(m.rfqs?.quantity)} ${esc(m.rfqs?.unit)} · ${esc(m.rfqs?.material)}</span><small>Match score ${m.match_score}% · ${q?'Quote '+status(q.status):'No quote yet'}</small></div><button class="btn" onclick="openQuote('${m.rfq_id}')">${q?'Edit quote':'Submit quote'} →</button></div>`}).join('')||'<div class="empty">No matched RFQs yet. Complete capabilities and machines.</div>'}</div>`);}
  async function admin(){const [{data:rfqs},{data:orders},{data:payouts}]=await Promise.all([db.from('rfqs').select('id,title,status,quantity,unit,created_at,categories(name)').order('created_at',{ascending:false}).limit(20),db.from('orders').select('id,order_number,total_amount,platform_fee,status,supplier_payout_amount,commission_percent').order('created_at',{ascending:false}).limit(20),db.from('supplier_payouts').select('id,status,amount')]);const gmv=(orders||[]).reduce((s,o)=>s+Number(o.total_amount||0),0),rev=(orders||[]).reduce((s,o)=>s+Number(o.platform_fee||0),0);root.innerHTML=shell('admin','Control Tower','Live operations, exceptions and commission ledger.',`<div class="stats"><div class="stat"><small>GMV</small><strong>${money(gmv)}</strong></div><div class="stat"><small>Platform revenue</small><strong>${money(rev)}</strong></div><div class="stat"><small>Open RFQs</small><strong>${rfqs?.length||0}</strong></div><div class="stat"><small>Pending payouts</small><strong>${(payouts||[]).filter(x=>x.status!=='paid').length}</strong></div></div><div class="exception"><div><span class="statusDot green"></span><b>Normal</b><p>Core workflow active</p></div><div><span class="statusDot amber"></span><b>Attention</b><p>Supplier verification / QC review</p></div><div><span class="statusDot red"></span><b>Critical</b><p>Disputes / failed payouts</p></div></div><div class="panelGrid"><div class="panel"><div class="panelTitle"><h3>RFQ queue</h3></div>${(rfqs||[]).map(r=>`<div class="job"><div><b>${esc(r.title)}</b><span>${esc(r.categories?.name||'')} · ${esc(r.quantity)} ${esc(r.unit)}</span><small>${status(r.status)}</small></div><button class="btn" onclick="openRFQDetail('${r.id}')">Inspect →</button></div>`).join('')||'<div class="empty">No RFQs.</div>'}</div><div class="panel"><div class="panelTitle"><h3>Commission ledger</h3><span class="badge">Server calculated</span></div>${(orders||[]).map(o=>`<div class="ledger"><div><b>${esc(o.order_number)}</b><span>${status(o.status)}</span></div><div><strong>${money(o.platform_fee)}</strong><small>${o.commission_percent}%</small></div></div>`).join('')||'<div class="empty compact">No orders.</div>'}</div></div>`);}
  async function renderLive(){if(location.hash!=='#dashboard')return;const p=await profile();if(!p)return;if(p.role==='admin')return admin();if(p.role==='supplier')return supplier();return buyer();}
  window.openLiveOrder=async id=>{const {data:o}=await db.from('orders').select('*,order_items(*),production_updates(*),quality_documents(*),shipments(*)').eq('id',id).single();if(!o){toast('Order not found');return;}const m=document.createElement('div');m.className='modalWrap';m.innerHTML=`<div class="modal wide"><div class="modalHead"><div><span class="badge">${status(o.status)}</span><b>${esc(o.order_number)}</b><small>Order value ${money(o.total_amount)} · Platform fee ${money(o.platform_fee)}</small></div><button class="close" onclick="this.closest('.modalWrap').remove()">×</button></div><div class="modalBody"><div class="timeline">${(o.production_updates||[]).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at)).map(x=>`<div class="tl done"><div class="lineDot"></div><div><b>${status(x.status)}</b><span>${x.progress_percent}% · ${esc(x.note||'')}</span></div></div>`).join('')||'<div class="empty compact">Production updates will appear here.</div>'}</div><div class="feature"><h3>Quality & shipment</h3><p>${(o.quality_documents||[]).length} quality documents · ${(o.shipments||[]).length} shipment record(s)</p></div></div></div>`;document.body.appendChild(m);};
  window.addEventListener('hashchange',renderLive);
  window.addEventListener('load',()=>setTimeout(renderLive,250));
  if(window.supabase)db.auth.onAuthStateChange(()=>setTimeout(renderLive,100));
})();
