(function(){
const heroImg='https://images.pexels.com/photos/386236/pexels-photo-386236.jpeg?auto=compress&cs=tinysrgb&w=1600';
const stages=[
 {title:'Post your requirement',desc:'Upload a drawing, choose the process, quantity and delivery date.',img:'https://images.pexels.com/photos/3822843/pexels-photo-3822843.jpeg?auto=compress&cs=tinysrgb&w=1400'},
 {title:'Find the right manufacturers',desc:'IndustrialConnect matches the job to relevant manufacturing capabilities.',img:'https://images.pexels.com/photos/2760243/pexels-photo-2760243.jpeg?auto=compress&cs=tinysrgb&w=1400'},
 {title:'Compare real quotations',desc:'See price, lead time, tooling, quality and commercial terms together.',img:'https://images.pexels.com/photos/3862632/pexels-photo-3862632.jpeg?auto=compress&cs=tinysrgb&w=1400'},
 {title:'Track production',desc:'Follow production milestones and quality evidence in the Order Room.',img:'https://images.pexels.com/photos/8985502/pexels-photo-8985502.jpeg?auto=compress&cs=tinysrgb&w=1400'},
 {title:'Receive and complete',desc:'Dispatch, delivery, acceptance and the complete transaction record stay connected.',img:'https://images.pexels.com/photos/4481327/pexels-photo-4481327.jpeg?auto=compress&cs=tinysrgb&w=1400'}
];
function renderV5(){
 const root=document.getElementById('app');
 root.innerHTML=`<div class="v5">
 <nav class="v5-nav"><a class="v5-brand" href="#"><img src="logo.svg"><span>Industrial<em>Connect</em></span></a><div class="v5-links"><a href="#how">How it works</a><a href="#network">Manufacturers</a><a href="#capabilities">Capabilities</a><a href="#experience">Order experience</a></div><div class="v5-actions"><button class="v5-btn light" onclick="openAuth('signin')">Sign in</button><button class="v5-btn primary" onclick="openRFQ()">Get started <span class="arrow">→</span></button></div></nav>
 <main>
 <section class="v5-hero"><div class="v5-wrap v5-hero-grid"><div><span class="v5-kicker"><i></i>India's modern manufacturing network</span><h1 class="v5-h1">Source parts.<br><span class="gradient">Not suppliers.</span></h1><p class="v5-lead">Post one requirement and move from drawing to competitive quotes, production tracking and delivery — without the procurement chaos.</p><div class="v5-hero-actions"><button class="v5-btn primary" onclick="openRFQ()">Start a requirement <span class="arrow">→</span></button><button class="v5-btn light" onclick="document.getElementById('experience').scrollIntoView({behavior:'smooth'})">Explore the workflow <span class="arrow">↗</span></button></div><div class="v5-pills"><span class="v5-pill">✓ Capability matching</span><span class="v5-pill">✓ Structured quotes</span><span class="v5-pill">✓ Production visibility</span><span class="v5-pill">✓ QC evidence</span></div></div><div class="v5-orbit"><div class="v5-photo"><img src="${heroImg}" alt="Modern industrial manufacturing"></div><div class="v5-floating v5-rfq"><small>LIVE REQUIREMENT</small><b>CNC precision shaft</b><div class="v5-meter"><span></span></div><small>3 manufacturers matched</small></div><div class="v5-floating v5-live"><small><span class="liveDot"></span>ORDER ROOM</small><strong>68%</strong><small>Production in progress · QC next</small></div></div></div></section>
 <section id="how" class="v5-section"><div class="v5-wrap"><div class="v5-head"><span class="v5-eyebrow">One connected workflow</span><h2 class="v5-h2">Your procurement,<br>finally feels simple.</h2><p class="v5-sub">Inspired by the best modern product experiences: fewer decisions, clearer progress and an interface that teaches you what to do next.</p></div><div class="v5-steps">${stages.map((s,i)=>`<article class="v5-step"><div class="n">0${i+1}</div><h3>${s.title.replace('your ','').replace('the right ','')}</h3><p>${s.desc}</p></article>`).join('')}</div></div></section>
 <section id="experience" class="v5-section soft"><div class="v5-wrap"><div class="v5-interactive"><div class="v5-control"><span class="v5-eyebrow">Interactive journey</span><h3>See what happens after you click “Start”.</h3><p>Tap any stage. The visual updates automatically so a first-time buyer understands the entire transaction before creating an account.</p><div class="v5-switches">${stages.map((s,i)=>`<button class="v5-switch ${i===0?'active':''}" data-stage="${i}"><b>0${i+1} · ${s.title}</b><span>${s.desc}</span></button>`).join('')}</div></div><div class="v5-stage"><img id="v5StageImg" src="${stages[0].img}" alt="Manufacturing workflow"><div class="v5-stage-copy"><span class="v5-eyebrow">IndustrialConnect workflow</span><h3 id="v5StageTitle">${stages[0].title}</h3><p id="v5StageDesc">${stages[0].desc}</p></div></div></div></div></section>
 <section id="capabilities" class="v5-section"><div class="v5-wrap"><div class="v5-head"><span class="v5-eyebrow">Built around the actual job</span><h2 class="v5-h2">From drawing to dispatch.</h2><p class="v5-sub">The product is designed around the transaction, not around a giant directory of suppliers.</p></div><div class="v5-cards"><article class="v5-card"><div class="mini-icon">01</div><h3>Smart RFQs</h3><p>Process, material, quantity, tolerance, delivery and drawings are captured in one clean requirement.</p></article><article class="v5-card"><div class="mini-icon">02</div><h3>Quote intelligence</h3><p>Compare commercial components instead of receiving disconnected messages and handwritten prices.</p></article><article class="v5-card"><div class="mini-icon">03</div><h3>Order Room</h3><p>Production, QC, documents, shipment, messages and acceptance remain connected to the order.</p></article></div></div></section>
 <section id="network" class="v5-section soft"><div class="v5-wrap"><div class="v5-trust"><div><span class="v5-eyebrow">Industrial network</span><h3>Built for manufacturers and procurement teams.</h3><p>Start narrow with Gujarat's CNC, VMC, casting and job-work ecosystem, then expand across India.</p></div><div class="v5-stat"><strong>RFQ</strong><span>Requirement-first</span></div><div class="v5-stat"><strong>QC</strong><span>Evidence attached</span></div><div class="v5-stat"><strong>₹</strong><span>Transparent commercial flow</span></div></div></div></section>
 <section class="v5-final"><div class="v5-wrap"><div class="v5-cta"><span class="v5-eyebrow" style="color:#bcecff">Your next manufacturing job</span><h2>Stop searching.<br>Start sourcing.</h2><p>Upload your first requirement and turn a manufacturing need into a structured procurement workflow.</p><button class="v5-btn light" onclick="openRFQ()">Post your requirement <span class="arrow">→</span></button></div></div></section>
 </main><footer class="v5-footer"><div class="v5-wrap v5-footer-in"><span>© 2026 IndustrialConnect India</span><span>Manufacturing procurement · Gujarat → India</span></div></footer></div>`;
 bindV5();
}
function bindV5(){let idx=0,timer;const img=document.getElementById('v5StageImg'),title=document.getElementById('v5StageTitle'),desc=document.getElementById('v5StageDesc'),buttons=[...document.querySelectorAll('.v5-switch')];function show(i){idx=i;img.style.opacity=0;setTimeout(()=>{img.src=stages[i].img;title.textContent=stages[i].title;desc.textContent=stages[i].desc;img.style.opacity=1},180);buttons.forEach((b,n)=>b.classList.toggle('active',n===i));}buttons.forEach((b,i)=>b.onclick=()=>{clearInterval(timer);show(i);timer=setInterval(()=>show((idx+1)%stages.length),4500)});timer=setInterval(()=>show((idx+1)%stages.length),4500)}
window.home=renderV5;
if(typeof window.go==='function')window.go('home');
})();