import Link from 'next/link';
import Hero3D from '@/components/hero-3d';
const capabilities=[['01','SOURCE','Post drawing, quantity, material and delivery window.'],['02','MATCH','Route requirements to relevant verified manufacturers.'],['03','PROTECT','Keep payment, evidence, production and disputes in one order room.'],['04','RELEASE','Buyer acceptance makes payout eligible and records platform commission.']];
const industries=['CNC Turning','CNC Milling / VMC','Investment Casting','Machinery Job Work','Fabrication','Laser Cutting','Sheet Metal','Grinding','Forging','Die Casting','Injection Moulding','Heat Treatment'];
export default function Home(){return <main><nav className="nav"><Link href="/" className="brand"><b>IC</b><span>INDUSTRIAL CONNECT</span></Link><div className="navlinks"><a href="#how">How it works</a><a href="#network">Network</a><a href="#protection">Protection</a></div><div className="navbuttons"><Link href="/dashboard/buyer/demo">Sign in</Link><Link className="primary" href="/dashboard/buyer/demo">Post requirement ↗</Link></div></nav>
<section className="hero"><div className="hero-copy"><small>INDIA'S INDUSTRIAL PROCUREMENT NETWORK</small><h1>Industrial sourcing,<br/><i>re-engineered.</i></h1><p>Connect real manufacturing capacity with real buyer requirements — then move from RFQ to delivery inside one protected transaction workflow.</p><div className="actions"><Link className="primary big" href="/dashboard/buyer/demo">Start a requirement →</Link><a className="ghost" href="#how">Explore the network ↓</a></div><div className="proof"><span><b>₹50K</b> pilot batches</span><span><b>₹50L+</b> contracts</span><span><b>48H</b> inspection</span></div></div><Hero3D/></section>
<div className="ticker">BUYER REQUIREMENT　→　SUPPLIER MATCH　→　QUOTE　→　PAYMENT　→　PRODUCTION　→　QC　→　DELIVERY　→　ACCEPTANCE</div>
<section className="manifesto" id="how"><small>01 / THE NEW INDUSTRIAL WORKFLOW</small><div><h2>Less chasing.<br/><em>More making.</em></h2><p>Replace fragmented calls, spreadsheets and payment uncertainty with a structured order layer. Requirements, quotes, production evidence, quality documents, logistics and acceptance stay connected to one order.</p></div></section>
<section className="process">{capabilities.map(([n,t,d])=><article key={n}><small>{n}</small><h3>{t}</h3><p>{d}</p><span>↗</span></article>)}</section>
<section className="visual"><span>CAPACITY / VERIFIED / IN MOTION</span><div className="rings"/><strong>From machine shop<br/><i>to delivered part.</i></strong></section>
<section className="protection" id="protection"><div><small>02 / TRANSACTION PROTECTION</small><h2>The order room<br/><em>is the source of truth.</em></h2></div><div><p>Protected marketplace payment state, production evidence, QC documents, dispatch proof, buyer inspection and dispute resolution — all auditable.</p>{['Funds secured','Material verified','Production evidenced','Buyer acceptance'].map((x,i)=><div className="status" key={x}><b>0{i+1}</b>{x}</div>)}</div></section>
<section className="network" id="network"><small>03 / INITIAL CAPACITY NETWORK</small><h2>Factories that<br/><em>actually make things.</em></h2><div className="grid">{industries.map((x,i)=><div key={x}><small>0{i+1}</small><b>{x}</b><span>GUJARAT / INDIA</span></div>)}</div></section>
<section className="final"><small>04 / START A TRANSACTION</small><h2>Have a part to make?<br/><em>Let's move it.</em></h2><p>Upload the requirement. Let the network handle matching and the order room handle the transaction.</p><Link className="primary big" href="/dashboard/buyer/demo">Post your requirement ↗</Link></section>
<footer><Link href="/" className="brand"><b>IC</b><span>INDUSTRIAL CONNECT</span></Link><p>Protected industrial procurement infrastructure.</p><span>© 2026 IndustrialConnect India</span></footer></main>}