'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';

type RFQ = { id:string; title:string; category:string; qty:string; city:string; deadline:string; status:string; quotes:number };
type Supplier = { name:string; city:string; capability:string; score:number; status:string; capacity:string };

const seedRfqs:RFQ[] = [
 {id:'RFQ-1048',title:'CNC turned shaft components',category:'CNC Turning',qty:'5,000 pcs',city:'Ahmedabad',deadline:'18 Oct',status:'Matching',quotes:4},
 {id:'RFQ-1047',title:'SS304 investment casting',category:'Investment Casting',qty:'2,500 pcs',city:'Pune',deadline:'21 Oct',status:'Quoting',quotes:7},
 {id:'RFQ-1046',title:'Laser-cut fabrication frames',category:'Fabrication',qty:'200 / month',city:'Vadodara',deadline:'24 Oct',status:'New',quotes:0},
 {id:'RFQ-1045',title:'VMC precision brackets',category:'CNC Milling / VMC',qty:'1,200 pcs',city:'Rajkot',deadline:'27 Oct',status:'Order ready',quotes:5},
];
const suppliers:Supplier[] = [
 {name:'Precision Motion Works',city:'Rajkot',capability:'CNC Turning · VMC',score:94,status:'Verified',capacity:'82%'},
 {name:'Shree CastTech Industries',city:'Rajkot',capability:'Investment Casting',score:91,status:'Verified',capacity:'64%'},
 {name:'Apex Fab Systems',city:'Ahmedabad',capability:'Laser · Bending · Welding',score:88,status:'Verified',capacity:'71%'},
 {name:'Vertex Engineering',city:'Vadodara',capability:'CNC Milling · Grinding',score:86,status:'Pending review',capacity:'55%'},
];
const nav = ['Overview','RFQs','Suppliers','Quotes','Orders','Production','Logistics','Quality','Payments','Commissions','Disputes','Analytics'];

export default function IndustrialControlCenter(){
 const [active,setActive]=useState('Overview');
 const [rfqs,setRfqs]=useState(seedRfqs);
 const [query,setQuery]=useState('');
 const [showCreate,setShowCreate]=useState(false);
 const [toast,setToast]=useState('');
 const filtered=useMemo(()=>rfqs.filter(r=>[r.id,r.title,r.category,r.city,r.status].join(' ').toLowerCase().includes(query.toLowerCase())),[rfqs,query]);
 const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(''),2200)};
 const createRfq=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);const next:RFQ={id:`RFQ-${1050+rfqs.length}`,title:String(fd.get('title')),category:String(fd.get('category')),qty:String(fd.get('qty')),city:String(fd.get('city')),deadline:String(fd.get('deadline')),status:'New',quotes:0};setRfqs([next,...rfqs]);setShowCreate(false);setActive('RFQs');notify('RFQ created and supplier matching queued.');};
 return <main className="ecosystem-shell">
  <aside className="ecosystem-sidebar">
   <Link href="/" className="eco-brand"><span className="brand-mark">I</span><span><b>INDUSTRIAL</b><strong>CONNECT</strong></span></Link>
   <div className="eco-role"><span>CONTROL TOWER</span><b>Owner / Admin</b><small>Procurement operating system</small></div>
   <nav>{nav.map(item=><button key={item} className={active===item?'active':''} onClick={()=>setActive(item)}><span className="nav-icon">{['◈','⌁','◉','◇','▣','⚙','⇢','✓','₹','%','!','◌'][nav.indexOf(item)]}</span>{item}</button>)}</nav>
   <div className="eco-sidebar-foot"><span>NETWORK STATUS</span><b><i/> Operational</b><small>All workflow modules online</small></div>
  </aside>
  <section className="eco-main">
   <header className="eco-topbar"><div><span className="eco-kicker">INDUSTRIAL CONNECT / {active.toUpperCase()}</span><h1>{active==='Overview'?'Procurement Control Tower':active}</h1></div><div className="eco-actions"><button className="eco-search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search RFQs, suppliers, orders..."/></button><button className="eco-notify" onClick={()=>notify('No new critical alerts.')}>◔</button><button className="eco-primary" onClick={()=>setShowCreate(true)}>+ New RFQ</button></div></header>
   {active==='Overview' && <Overview setActive={setActive} notify={notify}/>} 
   {active==='RFQs' && <RfqBoard rfqs={filtered} onNew={()=>setShowCreate(true)} onOpen={()=>setActive('Quotes')}/>} 
   {active==='Suppliers' && <SupplierBoard/>}
   {active==='Quotes' && <QuoteBoard notify={notify}/>} 
   {active==='Orders' && <OrderBoard/>}
   {active==='Production' && <Production/>}
   {active==='Logistics' && <Logistics/>}
   {active==='Quality' && <Quality/>}
   {active==='Payments' && <Payments/>}
   {active==='Commissions' && <Commissions/>}
   {active==='Disputes' && <Disputes/>}
   {active==='Analytics' && <Analytics/>}
  </section>
  {showCreate&&<div className="eco-modal-backdrop"><form className="eco-modal" onSubmit={createRfq}><div className="modal-head"><div><span className="eco-kicker">BUYER WORKSPACE</span><h2>Create new RFQ</h2></div><button type="button" onClick={()=>setShowCreate(false)}>×</button></div><label>Requirement title<input name="title" required placeholder="e.g. EN8 turned shaft"/></label><div className="form-two"><label>Category<select name="category"><option>CNC Turning</option><option>CNC Milling / VMC</option><option>Investment Casting</option><option>Fabrication</option><option>Sheet Metal</option><option>Grinding</option></select></label><label>Quantity<input name="qty" required placeholder="5,000 pcs"/></label></div><div className="form-two"><label>Delivery city<input name="city" required placeholder="Ahmedabad"/></label><label>Quote deadline<input name="deadline" required placeholder="18 Oct 2026"/></label></div><label>Technical notes<textarea name="notes" placeholder="Material, tolerance, drawing revision, quality requirements..."/></label><div className="modal-footer"><span>✓ Supplier matching will use capability, capacity, location and score.</span><button className="eco-primary">Create RFQ →</button></div></form></div>}
  {toast&&<div className="eco-toast">✓ {toast}</div>}
 </main>;
}

function Overview({setActive,notify}:{setActive:(x:string)=>void;notify:(x:string)=>void}){return <div className="eco-content"><div className="hero-strip"><div><span className="eco-kicker">LIVE OPERATING VIEW</span><h2>Control the requirement.<br/><em>Control the order.</em></h2><p>One workspace for buyer demand, supplier capacity, quotations, production, quality, logistics, payments and your commission ledger.</p></div><div className="hero-orbit"><span>RFQ</span><span>QUOTE</span><span>PO</span><span>QC</span><span>SHIP</span><b>IC</b></div></div><div className="metric-grid"><Metric label="Open RFQs" value="42" trend="+18%"/><Metric label="Matched suppliers" value="186" trend="+24%"/><Metric label="Orders in flight" value="17" trend="+6"/><Metric label="GMV pipeline" value="₹1.84Cr" trend="+31%"/><Metric label="Commission" value="₹6.42L" trend="+22%"/></div><div className="eco-grid-2"><section className="eco-panel"><div className="panel-head"><div><span className="eco-kicker">TODAY'S QUEUE</span><h3>Work that needs action</h3></div><button onClick={()=>setActive('RFQs')}>View all →</button></div><Queue label="4 RFQs" title="Need supplier matching" meta="CNC · Casting · Fabrication" action="MATCH"/><Queue label="7 quotes" title="Need buyer comparison" meta="3 high-fit quotes" action="COMPARE"/><Queue label="3 orders" title="Production evidence due" meta="2 due today" action="REVIEW"/><Queue label="2 cases" title="Quality / dispute review" meta="₹4.8L value protected" action="OPEN"/></section><section className="eco-panel"><div className="panel-head"><div><span className="eco-kicker">ECOSYSTEM HEALTH</span><h3>Control metrics</h3></div><button onClick={()=>setActive('Analytics')}>Analytics →</button></div><Health name="Buyer response rate" value="84%"/><Health name="Supplier quote acceptance" value="27%"/><Health name="On-time delivery" value="93%"/><Health name="Quality acceptance" value="97%"/><Health name="Repeat order rate" value="41%"/></section></div><section className="eco-panel"><div className="panel-head"><div><span className="eco-kicker">RECENT ACTIVITY</span><h3>Network timeline</h3></div><button onClick={()=>notify('Activity export prepared for download.')}>Export</button></div><div className="activity"><span>09:42</span><b>RFQ-1048</b><p>Matched 3 CNC suppliers in Rajkot</p><i>●</i></div><div className="activity"><span>09:18</span><b>ORD-2081</b><p>QC documents uploaded by supplier</p><i>●</i></div><div className="activity"><span>08:55</span><b>PAY-771</b><p>Buyer payment captured — ₹8.42L</p><i>●</i></div></section></div>}

function Metric({label,value,trend}:{label:string;value:string;trend:string}){return <div className="metric"><span>{label}</span><b>{value}</b><small>↗ {trend} vs last period</small></div>}
function Queue({label,title,meta,action}:{label:string;title:string;meta:string;action:string}){return <div className="queue"><div><b>{label}</b><strong>{title}</strong><span>{meta}</span></div><button>{action} →</button></div>}
function Health({name,value}:{name:string;value:string}){return <div className="health"><div><span>{name}</span><b>{value}</b></div><div className="health-bar"><i style={{width:value}}/></div></div>}
function RfqBoard({rfqs,onNew,onOpen}:{rfqs:RFQ[];onNew:()=>void;onOpen:()=>void}){return <div className="eco-content"><div className="page-actions"><div><span className="eco-kicker">BUYER DEMAND ENGINE</span><h2>RFQ marketplace</h2><p>Capture structured demand, match capability and move every opportunity toward a quote.</p></div><button className="eco-primary" onClick={onNew}>+ Create RFQ</button></div><div className="filter-row"><button className="selected">All RFQs · {rfqs.length}</button><button>New · 12</button><button>Matching · 8</button><button>Quoting · 15</button><button>Order ready · 7</button></div><div className="table-panel"><div className="table-head"><span>RFQ</span><span>Requirement</span><span>Buyer / Location</span><span>Deadline</span><span>Quotes</span><span>Status</span></div>{rfqs.map(r=><div className="table-row" key={r.id}><b>{r.id}</b><div><strong>{r.title}</strong><small>{r.category} · {r.qty}</small></div><span>{r.city}</span><span>{r.deadline}</span><b>{r.quotes}</b><button onClick={onOpen} className={'pill '+r.status.toLowerCase().replaceAll(' ','-')}>{r.status} →</button></div>)}</div></div>}
function SupplierBoard(){return <div className="eco-content"><div className="page-actions"><div><span className="eco-kicker">SUPPLIER NETWORK</span><h2>Capability marketplace</h2><p>Verified manufacturers, machine capacity and performance signals.</p></div><button className="eco-outline">+ Invite supplier</button></div><div className="supplier-cards">{suppliers.map(s=><article className="supplier-card" key={s.name}><div className="supplier-avatar">{s.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><span className="verified">✓ {s.status}</span><h3>{s.name}</h3><p>{s.capability}</p><small>{s.city} · Capacity loaded {s.capacity}</small></div><div className="score"><b>{s.score}</b><span>IC SCORE</span></div></article>)}</div></div>}
function QuoteBoard({notify}:{notify:(x:string)=>void}){const qs=[['RFQ-1048','Precision Motion Works','₹142 / pc','12 days','94'],['RFQ-1048','Vertex Engineering','₹137 / pc','15 days','86'],['RFQ-1048','Apex Precision','₹151 / pc','10 days','89'],['RFQ-1047','Shree CastTech Industries','₹318 / pc','21 days','91']];return <div className="eco-content"><div className="page-actions"><div><span className="eco-kicker">COMMERCIAL ENGINE</span><h2>Quote comparison</h2><p>Compare price, lead time, score and commercial terms from one requirement.</p></div></div><div className="quote-grid">{qs.map(q=><article className="quote-card" key={q[0]+q[1]}><span>{q[0]}</span><h3>{q[1]}</h3><div><b>{q[2]}</b><small>Unit price</small></div><div><b>{q[3]}</b><small>Lead time</small></div><div><b>{q[4]}</b><small>IC score</small></div><button onClick={()=>notify(`${q[1]} selected for negotiation.`)}>Select for negotiation →</button></article>)}</div></div>}
function OrderBoard(){const orders=[['ORD-2081','CNC shaft batch','Precision Motion Works','₹8.42L','PRODUCTION'],['ORD-2079','SS304 casting','Shree CastTech Industries','₹7.95L','QC'],['ORD-2075','Fabrication frames','Apex Fab Systems','₹4.18L','DISPATCHED']];return <div className="eco-content"><div className="page-actions"><div><span className="eco-kicker">ORDER ORCHESTRATION</span><h2>Orders in flight</h2><p>PO, payment, milestones, QC, dispatch and buyer acceptance.</p></div></div><div className="table-panel"><div className="table-head"><span>ORDER</span><span>Item</span><span>Supplier</span><span>Value</span><span>Stage</span></div>{orders.map(o=><div className="table-row" key={o[0]}><b>{o[0]}</b><strong>{o[1]}</strong><span>{o[2]}</span><b>{o[3]}</b><span className="pill matching">{o[4]}</span></div>)}</div></div>}
function Production(){return <Simple title="Production control" kicker="FACTORY EXECUTION" copy="Milestones, evidence and production progress stay attached to the order." cards={['Material received · 100%','Production started · 62%','In-process QC · 3 checkpoints','Dispatch readiness · 2 orders']}/>} 
function Logistics(){return <Simple title="Logistics command" kicker="SHIPMENT CONTROL" copy="Track pickup, LR, ETA, delivery proof and buyer acceptance from one order room." cards={['3 shipments in transit','2 pickups scheduled today','93% on-time delivery','4 PODs pending upload']}/>} 
function Quality(){return <Simple title="Quality & inspection" kicker="QUALITY CONTROL" copy="Keep inspection plans, reports, defects, evidence and buyer acceptance connected." cards={['12 inspections this week','97% acceptance rate','2 NCRs open','₹4.8L protected in review']}/>} 
function Payments(){return <Simple title="Payment control" kicker="FINANCIAL WORKFLOW" copy="Monitor buyer payment, protected funds, supplier payout eligibility and exceptions." cards={['₹42.8L captured','₹18.4L protected','₹12.6L payout eligible','2 payment exceptions']}/>} 
function Commissions(){return <Simple title="Commission ledger" kicker="REVENUE ENGINE" copy="Track your platform fee by RFQ, order, supplier, buyer and settlement status." cards={['₹6.42L earned','₹1.84Cr GMV pipeline','3.5% blended take rate','₹1.18L pending settlement']}/>} 
function Disputes(){return <Simple title="Dispute command" kicker="RISK & RESOLUTION" copy="Freeze affected workflows, preserve evidence and resolve quality or delivery disputes with an audit trail." cards={['2 open disputes','₹4.8L protected','0 unresolved > 7 days','100% evidence linked']}/>} 
function Analytics(){return <div className="eco-content"><div className="page-actions"><div><span className="eco-kicker">NETWORK INTELLIGENCE</span><h2>Industrial Connect analytics</h2><p>Measure demand, supply, conversion, delivery quality and platform revenue.</p></div></div><div className="chart-panel"><div className="chart-title"><b>GMV & commission trend</b><span>Last 8 periods</span></div><div className="bars">{[38,52,44,67,61,76,82,94].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>{i+1}</span></div>)}</div></div><div className="metric-grid"><Metric label="RFQ → quote" value="71%" trend="+8%"/><Metric label="Quote → order" value="24%" trend="+5%"/><Metric label="Repeat buyers" value="41%" trend="+11%"/><Metric label="Supplier utilisation" value="68%" trend="+9%"/></div></div>}
function Simple({title,kicker,copy,cards}:{title:string;kicker:string;copy:string;cards:string[]}){return <div className="eco-content"><div className="page-actions"><div><span className="eco-kicker">{kicker}</span><h2>{title}</h2><p>{copy}</p></div></div><div className="metric-grid simple-metrics">{cards.map((x,i)=>{const [a,b]=x.split(' · ');return <div className="metric" key={x}><span>{a}</span><b>{b||'Live'}</b><small>{i%2===0?'● Healthy':'● Monitoring'}</small></div>})}</div><div className="eco-panel large-empty"><div className="empty-orbit">IC</div><h3>Workflow module ready</h3><p>This control surface is wired for the production data model: orders, milestones, payments, disputes, payouts and audit events.</p></div></div>}
